"""Add fields

Revision ID: 35d1fcd2b874
Revises: 40e8447fdd21
Create Date: 2026-03-03 00:05:06.991511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35d1fcd2b874'
down_revision: Union[str, Sequence[str], None] = '40e8447fdd21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('experience_years', sa.Float(), nullable=False, server_default=sa.text('0.0')))
    # add new integer fields with a default to avoid nulls on existing rows
    op.add_column('employees', sa.Column('projects_completed', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('employees', sa.Column('client_satisfaction', sa.Float(), nullable=False, server_default=sa.text('4.0')))
    op.add_column('employees', sa.Column('teamwork_score', sa.Float(), nullable=False, server_default=sa.text('4.0')))
    op.alter_column('employees', 'revenue',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('employees', 'quality',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('employees', 'discipline',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'discipline',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('employees', 'quality',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('employees', 'revenue',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('employees', 'teamwork_score')
    op.drop_column('employees', 'client_satisfaction')
    op.drop_column('employees', 'projects_completed')
    op.drop_column('employees', 'experience_years')
    # ### end Alembic commands ###
