"""Initial

Revision ID: 40e8447fdd21
Revises: c9593f31df05
Create Date: 2026-02-20 21:03:04.636607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40e8447fdd21'
down_revision: Union[str, Sequence[str], None] = 'c9593f31df05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employees', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'department_id')
    # ### end Alembic commands ###
