"""Add fields

Revision ID: a81690dd6c9f
Revises: 35d1fcd2b874
Create Date: 2026-03-03 00:18:38.354348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a81690dd6c9f'
down_revision: Union[str, Sequence[str], None] = '35d1fcd2b874'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'revenue',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('employees', 'quality',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('employees', 'discipline',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('employees', 'projects_completed',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('employees', 'client_satisfaction',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('4.0'))
    op.alter_column('employees', 'teamwork_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('4.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'teamwork_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('4.0'))
    op.alter_column('employees', 'client_satisfaction',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('4.0'))
    op.alter_column('employees', 'projects_completed',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('employees', 'discipline',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('employees', 'quality',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('employees', 'revenue',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###
